### ISSUE TITLE
Update `ursa` dependency to latest version (0.3.7)

### ISSUE THREAD

**Issue by NicolasDP** [hyperledger/anoncreds-rs#123]
The current version of `ursa` that `anoncreds` depends on is 0.3.6. This version depends on `failure` and it triggers the different audit tools (`cargo deny` and GitHub security). I understand anoncreds don't actually use `failure` but this does not look good when running audit tools and creates unnecessary false warnings.

**Comment by TimoGlastra** [comment]
@blu3beri would it be easy to update the version of ursa we use?

**Comment by blu3beri** [comment]
Yeah I think we can move to `0.3.7`.

Looking at the change log, https://github.com/hyperledger/ursa/compare/v0.3.6...v0.3.7, it seems some very minor changes.

**Comment by NicolasDP** [comment]
Thanks, I was happy to do it in #124 but wanted to check with you first before adding a PR.
