### ISSUE TITLE
`anoncreds_create_revocation_registry` naming issue

### ISSUE THREAD

**Issue by cjhowland** [hyperledger/anoncreds-rs#127]
We're running into the following error while running ACA-Py unit tests that use anoncreds-rs: 
`undefined symbol: anoncreds_create_revocation_registry`. It appears that `anoncreds_create_revocation_registry` is called in `create_revocation_registry()` but is not defined elsewhere, and perhaps needs to be updated to `anoncreds_create_revocation_registry_def`. Any insights into this issue?

cc @dbluhm @burdettadam

**Comment by TimoGlastra** [comment]
`create_revocation_registry` has been replaced by `create_revocation_status_list`. The anoncreds rs implementation doesn't use deltas anymore in the public API (as the new specification also doesn't), but rather it now use the revocation status list model.

This hasn't been updated in the Python wrapper yet I assume.

https://github.com/hyperledger/anoncreds-rs/blob/main/src/ffi/revocation.rs#LL23C27-L23C27

I'll check with @blu3beri, as I know he was working on this

**Comment by blu3beri** [comment]
Yeah @TimoGlastra is correct here. I hope somewhere next week I can start fixing the issues with the Python wrapper.
