### ISSUE TITLE
[JS] JSI `asBool` is not available in RN 0.66

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#141]
`getBool` is available, they may have renamed it.

Check:
- whether `getBool` is available in newer versions
- whether we can directly use the value without unwrapping (`value ? 1 : 0`)

**Comment by blu3beri** [comment]
According to https://github.com/software-mansion/react-native-reanimated/pull/3961 it was added in 0.69. So we can just always use `getBool` and we will be fine. 

We could, later on, get rid of the double check whether its a boolean, inside the `jsiToValue` function as its also checked inside the `getBool` method with, possibly, a better error message.
