### ISSUE TITLE
Credential Request Entropy

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/anoncreds-rs#179]
Looking for some clarification around entropy. It's listed as `Optional()` in the `types.py` `Class` yet if I omit it and pass a `prover_did` instead, I get an error message `app.libs.anoncreds.error.AnoncredsError: entropy is required`.

Should this be marked as required in the python class?

**Comment by PatStLouis** [comment]
Furthermore, setting both `entropy` and `prover_did` yields `app.libs.anoncreds.error.AnoncredsError: Prover did and entropy must not both be supplied`.

So to use the `prover_did`, I need to provide the `prover_did` as `entropy` and set `prover_did` to `None`, rendering the `prover_did` attribute useless.

**Comment by genaris** [comment]
`prover_did` is used only when you are handling objects with 'legacy' identifiers, meaning by that those coming from Indy (e.g. DIDs that are 21-22 base58 characters long, or schemas/credDefIds matching the pattern from legacy Indy objects). In such case, you must only provide it (leaving `entropy` undefined).

On the other hand, when you are using fully qualified DIDs (or any other kind of identifiers that is not legacy), you must provide `entropy` and leave `prover_did`.

So the question here is... what kind of identifiers are you using for your issuer, schema, cred def, etc?

**Comment by PatStLouis** [comment]
Thanks for the clarification. In my scenario I'm using a `did:web` identifier ie: `did:web:domain:alice`, therefore I should be using the `entropy` attribute. My issue is about the `prover_did` attribute from the `CredentialRequest.create()` function which I suspect is not useable with the current code implementation. `entropy` should be marked as required and ideally `prover_did` removed from said function.

**Comment by PatStLouis** [comment]
Thanks for the clarification @TimoGlastra , I will close the issue
