### ISSUE TITLE
Generate binary for linux-aarch64

### ISSUE THREAD

**Issue by genaris** [hyperledger/anoncreds-rs#187]
Currently, the releases are creating binary artifacts for darwin in both x86_64 and aarch64, but for linux it only generates x86_64. This makes hard to work with linux-based docker images under a M1 Mac, as the expected binary is not found and we need to build the image in x86 mode.

**Comment by jleach** [comment]
+1 for this feature for the reasons mentioned above. Causes problems with devContainers on Apple Silicon (and probably Windows Surface Pro machines) because the container is arm64 but the proper binary does not exist.
