### ISSUE TITLE
Usage of timestamp override

### ISSUE THREAD

**Issue by genaris** [hyperledger/anoncreds-rs#191]
I'm trying to use the timestamp overrides for proofs that are requesting a non revoked range with both from and to after the actual revocation status list publishing date, but I cannot make it to work. 

What I do is to set up the first test in `wrappers/javascript/anoncreds-nodejs/test/api.test.ts` in a way that the proof request is:

```ts
const presentationRequest = PresentationRequest.fromJson({
      nonce,
      name: 'pres_req_1',
      version: '0.1',
      requested_attributes: {
        attr1_referent: {
          name: 'name',
          issuer: 'mock:uri',
        },
        attr2_referent: {
          name: 'sex',
        },
        attr3_referent: {
          name: 'phone',
        },
        attr4_referent: {
          names: ['name', 'height'],
        },
      },
      requested_predicates: {
        predicate1_referent: { name: 'age', p_type: '>=', p_value: 18 },
      },
      non_revoked: { from: 13, to: 200 },
    })
```

While `timestamp` for RevocationStatusList is 12 (as it was originally on the test). If I do so, I expect the verification to fail by just returning a "false" value, but it throws an `Invalid timestamp` error.

If I provide a nonRevokedIntervalOverride like the following one, I would expect it to return true:

```ts
    const verify = presentation.verify({
      presentationRequest,
      schemas: { ['mock:uri']: schema },
      credentialDefinitions: { ['mock:uri']: credentialDefinition },
      revocationRegistryDefinitions: { ['mock:uri']: revocationRegistryDefinition },
      revocationStatusLists: [revocationStatusList],
      nonRevokedIntervalOverride: [
        {
          overrideRevocationStatusListTimestamp: 12,
          requestedFromTimestamp: 13,
          revocationRegistryDefinitionId: 'mock:uri',
        },
      ],
    })
```

However it is still throwing the `Invalid timestamp` error. Am I using this at it is supposed to be?

**Comment by genaris** [comment]
Update: as it can be seen in #193, it seems that I'm using correctly but there is an error in JavaScript wrapper that is preventing verifier code to properly process this parameter.

**Comment by TimoGlastra** [comment]
Can be closed?
