### ISSUE TITLE
[Bug] Python Wrapper LinkSecret Invalid object handle

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/anoncreds-rs#194]
When attempting to transform a `LinkSecret` to json I get the following error:
`anoncreds.error.AnoncredsError: Invalid object handle`

Steps to reproduce:
```
link_secret = LinkSecret()
print(link_secret.to_dict())
```

**Comment by TimoGlastra** [comment]
Link secret is now a string. It should probably be updated in the python wrapper as well. @blu3beri do you know what needs to be chaned?

**Comment by PatStLouis** [comment]
Ok good to know. Ideally there should be a way to serialize the object and load it back. The `LinkSecret.load()` method expects a json as input and throws `undefined symbol: anoncreds_link_secret_from_json`. This makes it difficult to store/restore the link secret in-between data-flows such as creating a credential request and/or deriving a presentation.

**Comment by TimoGlastra** [comment]
There's no need anymore to serialize/dezerialize it. If you look at the JS wrapper it has a single LinkSecret.create which returns a string. All other methods now expect a string when you need to pass the link secret
