### ISSUE TITLE
Rename indy-credx to anoncreds

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#2]
We need to rename the `indy-credx` module to the `anoncreds` module

- [ ] Rename indy-credx directory to anoncreds
- [ ] Update Cargo.toml and remove indy terms, add anoncreds naming/terms
- [ ] Rename `impl_indy_object` to `impl_anoncreds_object`
- [ ] Rename `impl_indy_object_from_json` to `impl_anoncreds_object_from_json`
- [ ] Rename `IndyObject` to `AnonCredsObject`
- [ ] Rename `AnyIndyObject` to `AnyAnonCredsObject`
- [ ] Rename `IndyObjectId` to `AnonCredsObjectId`
- [ ] Rename `IndyObjectList` to `AnonCredsObjectList`

**Comment by dkulic** [comment]
Looks like I cannot assign myself on this task.

**Comment by swcurran** [comment]
You have an invitation to join the Hyperledger organization and/or become a maintainer. Once you accept that, you can assign the tasks, etc.  Please check your email associated with your GitHub account.

**Comment by dkulic** [comment]
I have also changed all function prefixes from credx_ to anoncreds_. Just to confirm if this is required?

I need help with these two attributes from Cargo.toml:
```
authors = ["Hyperledger Indy Contributors <indy@lists.hyperledger.org>"]
description = "Verifiable credential issuance and presentation for Hyperledger Indy (https://www.hyperledger.org/projects), which provides a distributed-ledger-based foundation for self-sovereign identity (https://sovrin.org)."
```

Not sure what to put there?

**Comment by TimoGlastra** [comment]
> Just to confirm if this is required?

Yes 👍 


I would say something like the following (@swcurran feel free to amend):

```
authors = ["Hyperledger AnonCreds Contributors <anoncreds@lists.hyperledger.org>"]
description = "Verifiable credential issuance and presentation for Hyperledger AnonCreds (https://www.hyperledger.org/projects), which provides a foundation for self-sovereign identity."
```

**Comment by swcurran** [comment]
Looks pretty good.  Please change the landing page to ""https://www.hyperledger.org/use/anoncreds" and I'll make sure that gets created in the next few days.

Interesting idea for the authors -- seems like a reasonable idea.

**Comment by dkulic** [comment]
I think this PR is ready for review. Do not know who to put for it?
https://github.com/hyperledger/anoncreds-rs/pull/14
