### ISSUE TITLE
`tailsLocation` is pulling double duty

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/anoncreds-rs#220]
The `tailsLocation` attribute on rev reg defs has an unfortunate characteristic. When using the rev reg def with the library, this needs to be the local filesystem path to the tails file. When we register the definition, this needs to be the public URI to the tails file. This leads to needing to swap the value depending on what operation you're doing which is both inconvenient and confusing.

In the Indy Credx library, this was handled by having a separate argument for the tails path in methods that required it. For example: https://github.com/hyperledger/indy-shared-rs/blob/main/indy-credx/src/ffi/revocation.rs#L126-L133

I think going back to having the tails path as a separate parameter is probably the right choice with the side benefit of the anoncreds-rs library more closely resembling the library it's replacing.

**Comment by blu3beri** [comment]
Yeah that makes sense to me.

> I think going back to having the tails path as a separate parameter is probably the right choice with the side benefit of the anoncreds-rs library more closely resembling the library it's replacing.

I would rather not keep it as close as possible to the old API if changes can benefit this API.

**Comment by dbluhm** [comment]
Yes, I agree that we should improve the API where it makes sense. But I will say that the Indy Credx library API was already an improvement on the Indy SDK API and has been successfully in use for some time already in at least ACA-Py; I think this should be factored into improvements we're considering. I think this is a good example of an instance where it seemed like the API could be improved but it came back to bite us as we moved on to integration with agents.

**Comment by dbluhm** [comment]
Recent updates to Indy CredX should be adapted to this library as well. Rather than needing to persist a tails file to the filesystem indefinitely, @andrewwhitehead recently improved the interface of Indy CredX to accept the registry private keys and the required G2 points are generated on demand (or something like that).

**Comment by andrewwhitehead** [comment]
I think this may be resolved now? It looks like the tails path is only required for `create_or_update_revocation_state`, and in that case it is passed separately from the credential definition.

**Comment by dbluhm** [comment]
Yep, I think you're right. Thanks!
