### ISSUE TITLE
Strings not freed in the JS wrapper?

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/anoncreds-rs#236]
I don't see any references to `anoncreds_string_free`, but this is likely required for all strings coming from the FFI layer. This could be a significant memory leak over time.

**Comment by berendsliedrecht** [comment]
Yeah that does not seem to be too good. I think we have three solutions but they all have some disadvantages

1. Expose `string_free` publicly and allow the consumer to deal with it.
  - Downside is that this is quite the uncommon pattern in JS and likely they will still forget some allocations.
2. Within the wrapper copy the value and immediately call it (it might even already be copied `ffi-napi` and c++ side).
  - Would still require all manual frees but at least we control it and not the consumer.
 3. Wait for Typescript 5.2 to be stable as it introduces the `using` keyword which would finally allow a cleanup function to be ran when it goes out-of-scope.
   - The best option by far, but I am unsure of the timeline (https://github.com/microsoft/TypeScript/issues/54298).

IMO it is okay to wait for typeScript 5.2 and leave this as-is for now.

**Comment by genaris** [comment]
> 3\. Wait for Typescript 5.2 to be stable as it introduces the `using` keyword which would finally allow a cleanup function to be ran when it goes out-of-scope.
> 
> * The best option by far, but I am unsure of the timeline ([TypeScript 5.2 Iteration Plan microsoft/TypeScript#54298](https://github.com/microsoft/TypeScript/issues/54298)).

Well, if that iteration plan is accurate, it will be out in 4 days from now! So definitely it's worth waiting a bit and doing not only this but also for object handle clear() methods.

If not, I'd go for option 2.

**Comment by andrewwhitehead** [comment]
I think the wrapper copies these FFI string buffers to Strings anyway, so it should be possible to free the reference before returning. I noticed later that this would apply to `anoncreds_buffer_free` as well, for binary buffers.
