### ISSUE TITLE
Replace the revocation registry delta methods with the new revocation list data model API

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#24]
This should probably be split up into multiple issues

Relevant spec issue: https://github.com/hyperledger/anoncreds-spec/issues/108

**Comment by TimoGlastra** [comment]
@whalelephant This is the issue for the revocation list model implementation in AnonCreds rs. As you see, not much here yet....

**Comment by blu3beri** [comment]
Is this finished once #74 is done? After that we only deal with:

- RevocationRegistryDefinitions
- RevocationRegistries
- RevocationStatusList
- RevocationState

(and their associated identifiers).

**Comment by TimoGlastra** [comment]
@whalelephant can you verify if this is correct?
