### ISSUE TITLE
ImportError create_link_secret from anoncreds-test 0.1.0.dev10

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/anoncreds-rs#246]
I'm testing out the `anoncreds-test 0.1.0.dev10` pip package published on testpypi and am unable to import the `create_link_secret` function.

It's missing from the `.bindings import` in the `__init__.py` file. Adding it fixes the issue. 

Steps to reproduce:
```
pip install -i https://test.pypi.org/simple/ anoncreds-test
from anoncreds_test import create_link_secret
```

**Comment by andrewwhitehead** [comment]
It seems to be there in main, so maybe you just need the new release to be published.
