### ISSUE TITLE
release assets

### ISSUE THREAD

**Issue by joyride9999** [hyperledger/anoncreds-rs#275]
In the release assets should provide also *.lib and *.dll.lib files.
They are needed for compilation.

**Comment by berendsliedrecht** [comment]
I do not see it as a responsibility of this library to provide the associated libaries, e.g. openssl, as they are common system dependencies. If you do not have these installed, you can use the `vendored` feature to build them for you.

**Comment by joyride9999** [comment]
i am not reffering to openssl or other libraries, i am reffering to the main artefacts of the build process that is anoncreds.*, that is lib files, dll.lib, .so, .a  files
