### ISSUE TITLE
Revocation Registry ID validation is failing

### ISSUE THREAD

**Issue by ianco** [hyperledger/anoncreds-rs#312]
I think the fix to the DID validation (#307) broke the revocation registry ID validation, we are seeing these errors now on the aca-py integration tests:

```
7hAcme.agent | anoncreds.error.AnoncredsError: type: RevocationRegistryDefinitionId, identifier: 2oEZfAdHA6vETfASonFe57:4:2oEZfAdHA6vETfASonFe57:3:CL:288602:Acme.agent.Schema_DriversLicense_v2:CL_ACCUM:0 is invalid. It MUST be a URI or legacy identifier.
7hAcme.agent | 2024-01-25 17:06:50,457 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
```

The tests were passing with the `dev7` version but are failing with the `dev8` version.

**Comment by swcurran** [comment]
That is weird....

I guess I didn't understand the scope of the change we were doing.  Sounds like the scope was beyond the `prover_did` validation? 

I thought we had to explicitly add support for dev8, but is it automatically picked up?

We need to get a fix in for that ASAP, as this will be a significant break. 

@andrewwhitehead @ianco , please coordinate.

**Comment by andrewwhitehead** [comment]
It's the change to the URI recognition. It seems like the legacy ID recognition was failing, and it was being recognized as a general URI when it's not really. Seems like another test is needed in the library.

**Comment by ianco** [comment]
Can we get a `dev9` release so we can test this out?

**Comment by TimoGlastra** [comment]
I can do it tomorrow morning. if you can create A PR to update the version already that'll help! (Otherwise i can also do that tomorrow)

**Comment by swcurran** [comment]
Created and tests are running: #314

**Comment by TimoGlastra** [comment]
Release cooking … https://github.com/hyperledger/anoncreds-rs/releases/tag/v0.2.0-dev.9
