### ISSUE TITLE
Data Integrity Proof Cryptosuite naming

### ISSUE THREAD

**Issue by 2mau** [hyperledger/anoncreds-rs#315]
I know this has been discussed before, but I would like to reiterate the current use of Cryptosuite properties when working with w3c credentials and presentations.

Currently, we use `anoncreds-vc` for credentials, `anoncredspres-vc` for derived credentials, and `anoncredspresvp-2023` for presentations.

There are a few issues with this approach.
1. Having multiple different identifiers here naturally introduces some complexity.
    E.g., checks and mappings for these identifiers.
2. It is not really in line with what the Data Integrity spec defines as a crypto suite,
    an identifier for a `set of specific cryptographic primitives,` as we don't change the cryptographic primitives.
3. Also, other crypto suites supporting selective disclosure don't follow this approach, e.g., `https://www.w3.org/TR/vc-di-bbs/`.

During a working group call, it was suggested to use only a single crypto suite value,
e.g. by encoding the required metadata in the proofValue. I think it would make sense to move in this direction.

**Comment by swcurran** [comment]
Makes sense.  I had been thinking about the need to know the crypto suite in combination only with the `proofValue` field. But I gather that you are saying the context of *where* the cyrptosuite is referenced would also be considered and is sufficient for use in interpreting the `proofValue`.

In the meetings, we didn’t get to this issue to discuss it and so it never changed.

FYI — looking at the code, it appears the strings used are `anoncredsvc-2023`, `vc-anoncredspres2023`, and `anoncredspresvp-2023`

**Comment by swcurran** [comment]
@Artemkaaas — would you be able to make this change?

@ianco @andrewwhitehead @tra371 @gvelez17

**Comment by swcurran** [comment]
Got it.  So sniff the `proofValue` and process it according to that encoding.
