### ISSUE TITLE
Using index 0 for issuing a credential gives "AnoncredsError: Invalid state: Revocation index is outside of valid range"

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#337]
It should be possible to issue a credential with revocation registry 0 right? Or does it start at 1?

I experienced this in the JS wrapper, not sure if it's present elsewhere.

**Comment by TimoGlastra** [comment]
cc @berendsliedrecht

**Comment by andrewwhitehead** [comment]
It does start at 1 by convention.
