### ISSUE TITLE
Add `issuerId` to all anoncreds objects that are registered on the vdr

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#39]
See hyperledger/anoncreds-spec#126 and https://github.com/hyperledger/anoncreds-spec/issues/116

Should follow rules as defined in spec (e.g. issuerId from cred def MUST be same as issuerId from revocation registry definition), same with revocation list

**Comment by blu3beri** [comment]
After #56 is merged, just revocation list is left. (just to keep track).
