### ISSUE TITLE
Figure out what to do with indy-wql

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#5]
The indy-shared-rs repository contains an implementation of the wallet query language (WQL). It seems the wql module is used currently used by Aries Askar and Indy CredX. The new AnonCreds library will also need to support . 

As Aries Askar now depends on indy_wql, it may make sense to make both AnonCreds and Aries Askar depend on WQL. Need to gather some feedback on this approach.

- [ ] Determine where the wql code will live (indy-shared-rs, anoncreds, aries-askar)
- [ ] Determine whether the WQL needs to be standardized as part of AnonCreds
  - It could also be a separate specification, with separate implementation

If we keep it in here, we should rename it to anoncreds-wql (or maybe even just wallet_query_language) 

Discussed:
- Move implementation to Aries Askar (ask Andrew Whitehead)
- Interface in anoncreds(-utils) that is only used for validation in proof request (can be really simple)

**Comment by TimoGlastra** [comment]
@andrewwhitehead I discussed this with @dkulic, @victormartinez-work and @blu3beri and we think it would be best to move the WQL implementation (only seems to be one file) to Askar itself, and add a minimal implementation based on what is needed for proof requests to the anoncreds lib.

Is that approach okay with you? We would like to keep dependencies between projects where not needed as low as possible

**Comment by blu3beri** [comment]
Once [this](https://github.com/hyperledger/aries-askar/pull/63) is merged the ticket is completed.
