### ISSUE TITLE
Rename indy-data-types to anoncreds-data-types

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#6]
We need to rename the `indy-data-types` module to the `anoncreds-data-types` module

- [ ] Rename indy-data-types directory to anoncreds-data-types
- [ ] Update Cargo.toml and remove indy terms, add anoncreds naming/terms

**Comment by dkulic** [comment]
For some reason I am unable to link pull request: https://github.com/hyperledger/anoncreds-rs/pull/18
