### ISSUE TITLE
RevocationStatusList - remaining tasks

### ISSUE THREAD

**Issue by whalelephant** [hyperledger/anoncreds-rs#71]
1. Missing FFI for the below interactions which needs to be implemented
```
create_revocation_status_list, 
update_revocation_status_list, 
update_revocation_status_list_timestamp_only
```
2. Current there is no tests that uses `update_revocation_status_list_timestamp_only` - test to be added

**Comment by blu3beri** [comment]
@whalelephant Is this finished? Not sure about point 2.
