### ISSUE TITLE
Release AnonCreds for NodeJS to NPM

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#77]
- Add `@hyperledger` prefix
- Make sure the registration is consistent Askar & Indy VDR
- Set the correct version
- add the `anoncreds` prefix to the folder names

**Comment by blu3beri** [comment]
All the tasks will be finished by #81 

Just have to create a GitHub pre-release and it should be good :).

**Comment by TimoGlastra** [comment]
The token has been added!
