### ISSUE TITLE
Consistency between link secret and master secret

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/anoncreds-rs#88]
The credential_defintion must use master secret for backwards compat. But the spec uses link secret. The api currently also uses master. What should we use?

**Comment by genaris** [comment]
Another field that must be considered is `prover_did`, as the spec refers to the _prover_ as a _holder_.

It would be nice to discuss about this in these days, as we have the first releases and the first implementations using `anoncreds-rs` API are being developed.

Maybe, if backwards compatibilty is a big concern in AnonCreds 1.0, it might be fine to keep these legacy terms and move forward to the new ones in the next version that is not supposed to keep compatibility?

**Comment by TimoGlastra** [comment]
As Prover did is deprecated, so I think we can leave it as is for legacy indy objects, and not use it for the new AnonCreds spec

**Comment by TimoGlastra** [comment]
Discussed on AFJ call. Name is now link secret. We'll use that in AFJ public API as well. Only in places where we need to use master secret for backwards compat (e.g. the cred def registered on the ledger) we will use `master_secret` (Example cred def using `master_secret`: https://indyscan.io/tx/SOVRIN_MAINNET/domain/155694)

**Comment by blu3beri** [comment]
What would this fix entail? We accept `master_secret` as input of an object but only create objects with `link_secret`?
